module.exports={
  'data':{
    "type": 1,
    "name": "uptime","name_localizations": {"id": "uptime","da": "oppetid","de": "Betriebszeit","en-GB": "uptime","en-US": "uptime","es-ES": "tiempo de actividad","es-419": "tiempo de actividad","fr": "durée de la baisse","hr": "radno vrijeme","it": "Uptime","lt": "UPTITAS","hu": "beutazási idő","nl": "uptime","no": "oppetid","pl": "czas aktu","pt-BR": "tempo de atividade","ro": "timp de funcționare","fi": "käyttöaika","sv-SE": "drifttid","vi": "thời gian hoạt động","tr": "çalışma süresi","cs": "Uptime","el": "χρόνος ανοικτής","bg": "Време за работа","ru": "время безотказной работы","uk": "час роботи","hi": "अपटाइम","th": "เวลาทำงาน","zh-CN": "正常运行时间","ja": "稼働時間","zh-TW": "正常運行時間","ko": "가동 시간"},
    "description": "Curious how long I've been awake? This tells you my uptime since my last restart.","description_localizations": {"id": "Penasaran berapa lama saya terjaga? ","da": "Er du nysgerrig efter, hvor længe jeg har været vågen? ","de": "Neugierig, wie lange ich wach war? ","en-GB": "Curious how long I've been awake? This tells you my uptime since my last restart.","en-US": "Curious how long I've been awake? This tells you my uptime since my last restart.","es-ES": "¿Curioso cuánto tiempo he estado despierto? ","es-419": "¿Curioso cuánto tiempo he estado despierto? ","fr": "Curieux depuis combien de temps je suis éveillé? ","hr": "Znatiželjno koliko sam bio budan? ","it": "Curioso da quanto tempo sono sveglio? ","lt": "Smalsu, kiek laiko aš budėjau? ","hu": "Kíváncsi, meddig voltam ébren? ","nl": "Benieuwd hoe lang ik wakker ben? ","no": "Nysgjerrig hvor lenge jeg har vært våken? ","pl": "Ciekawe, jak długo nie śpię? ","pt-BR": "Curioso quanto tempo estou acordado? ","ro": "Curios de cât timp am fost treaz? ","fi": "Utelias kuinka kauan olen ollut hereillä? ","sv-SE": "Nyfiken hur länge jag har varit vaken? ","vi": "Tò mò tôi đã thức bao lâu? ","tr": "Ne kadar zamandır uyanık olduğumu merak ediyor musun? ","cs": "Zajímavé, jak dlouho jsem vzhůru? ","el": "Περίεργος πόσο καιρό ήμουν ξύπνιος; ","bg": "Любопитно колко дълго съм буден? ","ru": "Любопытно, как долго я не спал? ","uk": "Цікаво, як довго я прокинувся? ","hi": "जिज्ञासु मैं कब तक जाग रहा हूँ? ","th": "อยากรู้ว่าฉันตื่นมานานแค่ไหน? ","zh-CN": "好奇我醒了多久？","ja": "私がどれほど目を覚ましているのか興味がありますか？","zh-TW": "好奇我醒了多久？自上次重新開始以來，這告訴您我的正常運行時間。","ko": "내가 얼마나 깨어 있었는지 궁금해? "
                                                                                                                                    }
  },
  'code': `I've been up for $parseMS[$uptime], while my the machine I am hosted on, has been up for $parseMS[$osUptime].`
}
