module.exports = {
  data: {
    "name": "bug-report",
    "description": "Found a bug? Report now!",
    "options": [
      {
        "type": 3,
        "name": "description",
        "description": "Detailed description of the bug",
        "required": true,
        "name_localizations": {
          "id": "keterangan",
          "da": "beskrivelse",
          "de": "beschreibung",
          "en-GB": "description",
          "en-US": "description",
          "es-ES": "descripcion",
          "es-419": "descripcion",
          "fr": "description",
          "hr": "opis",
          "it": "descrizione",
          "lt": "aprasymas",
          "hu": "leiras",
          "nl": "beschrijving",
          "no": "beskrivelse",
          "pl": "opis",
          "pt-BR": "descricao",
          "ro": "descriere",
          "fi": "kuvaus",
          "sv-SE": "beskrivning",
          "vi": "mo-ta",
          "tr": "tanim",
          "cs": "popis",
          "el": "perigrafi",
          "bg": "opisanie",
          "ru": "opisanie",
          "uk": "opis",
          "hi": "vivaran",
          "th": "kam-athibai",
          "zh-CN": "miaoshu",
          "ja": "setsumei",
          "zh-TW": "miaoshu",
          "ko": "seolmyeong"
        }
      },
      {
        "type": 3,
        "name": "severity",
        "description": "Impact level of the bug",
        "required": true,
        "choices": [
          {
            "value": "High",
            "name": "High",
            "name_localizations": {
              "id": "tinggi",
              "da": "hoj",
              "de": "hoch",
              "en-GB": "high",
              "en-US": "high",
              "es-ES": "alto",
              "es-419": "alto",
              "fr": "eleve",
              "hr": "visoko",
              "it": "alto",
              "lt": "aukštas",
              "hu": "magas",
              "nl": "hoog",
              "no": "hoy",
              "pl": "wysokie",
              "pt-BR": "alta",
              "ro": "inalt",
              "fi": "korkea",
              "sv-SE": "hog",
              "vi": "cao",
              "tr": "yuksek",
              "cs": "vysoka",
              "el": "ypsili",
              "bg": "visoka",
              "ru": "vysokiy",
              "uk": "vysokiy",
              "hi": "uchch",
              "th": "sung",
              "zh-CN": "gao",
              "ja": "takai",
              "zh-TW": "gao",
              "ko": "nopeum"
            }
          },
          {
            "value": "Medium",
            "name": "Medium",
            "name_localizations": {
              "id": "sedang",
              "da": "medium",
              "de": "medium",
              "en-GB": "medium",
              "en-US": "medium",
              "es-ES": "medio",
              "es-419": "medio",
              "fr": "moyen",
              "hr": "srednji",
              "it": "medio",
              "lt": "vidutinis",
              "hu": "kozepes",
              "nl": "gemiddeld",
              "no": "medium",
              "pl": "srednie",
              "pt-BR": "medio",
              "ro": "mediu",
              "fi": "keskitaso",
              "sv-SE": "medium",
              "vi": "trung-binh",
              "tr": "orta",
              "cs": "stredni",
              "el": "mesaio",
              "bg": "sreden",
              "ru": "sredniy",
              "uk": "seredniy",
              "hi": "madhyam",
              "th": "klang",
              "zh-CN": "zhong",
              "ja": "chuu",
              "zh-TW": "zhong",
              "ko": "junggan"
            }
          },
          {
            "value": "Low",
            "name": "Low",
            "name_localizations": {
              "id": "rendah",
              "da": "lav",
              "de": "niedrig",
              "en-GB": "low",
              "en-US": "low",
              "es-ES": "bajo",
              "es-419": "bajo",
              "fr": "faible",
              "hr": "nisko",
              "it": "basso",
              "lt": "zemas",
              "hu": "alacsony",
              "nl": "laag",
              "no": "lav",
              "pl": "niski",
              "pt-BR": "baixo",
              "ro": "scazut",
              "fi": "matala",
              "sv-SE": "lag",
              "vi": "thap",
              "tr": "dusuk",
              "cs": "nizka",
              "el": "chamili",
              "bg": "nisko",
              "ru": "nizkiy",
              "uk": "nyzkiy",
              "hi": "kam",
              "th": "tam",
              "zh-CN": "di",
              "ja": "hikui",
              "zh-TW": "di",
              "ko": "naj-eum"
            }
          }
        ],
        "name_localizations": {
          "id": "tingkat-keparahan",
          "da": "alvorlighed",
          "de": "schwere",
          "en-GB": "severity",
          "en-US": "severity",
          "es-ES": "gravedad",
          "es-419": "gravedad",
          "fr": "gravite",
          "hr": "ozbiljnost",
          "it": "gravita",
          "lt": "sunkumas",
          "hu": "sulyossag",
          "nl": "ernst",
          "no": "alvorlighetsgrad",
          "pl": "powaga",
          "pt-BR": "gravidade",
          "ro": "severitate",
          "fi": "vakavuus",
          "sv-SE": "strenghet",
          "vi": "muc-do-nghiem-trong",
          "tr": "siddet",
          "cs": "zavaznost",
          "el": "afstirotheta",
          "bg": "tezhest",
          "ru": "tyazhest",
          "uk": "tyazhkist",
          "hi": "gambhirta",
          "th": "kwarm-runraeng",
          "zh-CN": "yanzhong-chengdu",
          "ja": "judaido",
          "zh-TW": "yanzhong-chengdu",
          "ko": "simgakseong"
        }
      },
      {
        "type": 3,
        "name": "category",
        "description": "The Gluo project you want to make a report about",
        "required": true,
        "choices": [
          {
            "value": "Web",
            "name": "Web App",
            "name_localizations": {
              "id": "aplikasi-web",
              "da": "webapp",
              "de": "web-app",
              "en-GB": "web-app",
              "en-US": "web-app",
              "es-ES": "app-web",
              "es-419": "app-web",
              "fr": "app-web",
              "hr": "web-aplikacija",
              "it": "app-web",
              "lt": "web-programa",
              "hu": "webalkalmazas",
              "nl": "web-app",
              "no": "web-app",
              "pl": "aplikacja-web",
              "pt-BR": "app-web",
              "ro": "aplicatie-web",
              "fi": "verkkosovellus",
              "sv-SE": "webbapp",
              "vi": "ung-dung-web",
              "tr": "web-uygulamasi",
              "cs": "webova-aplikace",
              "el": "efarmogi-web",
              "bg": "ueb-prilozhenie",
              "ru": "veb-prilozhenie",
              "uk": "veb-dodatok",
              "hi": "veb-aip",
              "th": "aep-web",
              "zh-CN": "wang-luo-ying-yong",
              "ja": "uebbu-apuri",
              "zh-TW": "wang-luo-ying-yong",
              "ko": "web-aep"
            }
          },
          {
            "value": "App",
            "name": "Android App",
            "name_localizations": {
              "id": "aplikasi-android",
              "da": "android-app",
              "de": "android-app",
              "en-GB": "android-app",
              "en-US": "android-app",
              "es-ES": "app-android",
              "es-419": "app-android",
              "fr": "app-android",
              "hr": "android-aplikacija",
              "it": "app-android",
              "lt": "android-programa",
              "hu": "android-alkalmazas",
              "nl": "android-app",
              "no": "android-app",
              "pl": "aplikacja-android",
              "pt-BR": "app-android",
              "ro": "aplicatie-android",
              "fi": "android-sovellus",
              "sv-SE": "android-app",
              "vi": "ung-dung-android",
              "tr": "android-uygulamasi",
              "cs": "android-aplikace",
              "el": "efarmogi-android",
              "bg": "android-prilozhenie",
              "ru": "android-prilozhenie",
              "uk": "android-dodatok",
              "hi": "aintroit-aip",
              "th": "aep-android",
              "zh-CN": "anzhuo-ying-yong",
              "ja": "andoroido-apuri",
              "zh-TW": "anzhuo-ying-yong",
              "ko": "android-aep"
            }
          },
          {
            "value": "App2",
            "name": "New App",
            "name_localizations": {
              "id": "aplikasi-baru",
              "da": "ny-app",
              "de": "neue-app",
              "en-GB": "new-app",
              "en-US": "new-app",
              "es-ES": "nueva-app",
              "es-419": "nueva-app",
              "fr": "nouvelle-app",
              "hr": "nova-aplikacija",
              "it": "nuova-app",
              "lt": "nauja-programa",
              "hu": "uj-alkalmazas",
              "nl": "nieuwe-app",
              "no": "ny-app",
              "pl": "nowa-aplikacja",
              "pt-BR": "novo-app",
              "ro": "aplicatie-noua",
              "fi": "uusi-sovellus",
              "sv-SE": "ny-app",
              "vi": "ung-dung-moi",
              "tr": "yeni-uygulama",
              "cs": "nova-aplikace",
              "el": "nea-efarmogi",
              "bg": "novo-prilozhenie",
              "ru": "novoe-prilozhenie",
              "uk": "noviy-dodatok",
              "hi": "naya-aip",
              "th": "aep-mai",
              "zh-CN": "xin-ying-yong",
              "ja": "atarashii-apuri",
              "zh-TW": "xin-ying-yong",
              "ko": "saeroun-aep"
            }
          },
          {
            "value": "Api4",
            "name": "Old API",
            "name_localizations": {
              "id": "api-lama",
              "da": "gammel-api",
              "de": "alte-api",
              "en-GB": "old-api",
              "en-US": "old-api",
              "es-ES": "api-antigua",
              "es-419": "api-antigua",
              "fr": "ancienne-api",
              "hr": "stari-api",
              "it": "vecchia-api",
              "lt": "sena-api",
              "hu": "regi-api",
              "nl": "oude-api",
              "no": "gammel-api",
              "pl": "stara-api",
              "pt-BR": "api-antiga",
              "ro": "api-veche",
              "fi": "vanha-api",
              "sv-SE": "gammal-api",
              "vi": "api-cu",
              "tr": "eski-api",
              "cs": "stara-api",
              "el": "palia-api",
              "bg": "stara-api",
              "ru": "staraya-api",
              "uk": "stara-api",
              "hi": "purana-api",
              "th": "api-kao",
              "zh-CN": "jiu-api",
              "ja": "furui-api",
              "zh-TW": "jiu-api",
              "ko": "ye-api"
            }
          },
          {
            "value": "Api5",
            "name": "New API",
            "name_localizations": {
              "id": "api-baru",
              "da": "ny-api",
              "de": "neue-api",
              "en-GB": "new-api",
              "en-US": "new-api",
              "es-ES": "nueva-api",
              "es-419": "nueva-api",
              "fr": "nouvelle-api",
              "hr": "novi-api",
              "it": "nuova-api",
              "lt": "nauja-api",
              "hu": "uj-api",
              "nl": "nieuwe-api",
              "no": "ny-api",
              "pl": "nowa-api",
              "pt-BR": "nova-api",
              "ro": "api-noua",
              "fi": "uusi-api",
              "sv-SE": "ny-api",
              "vi": "api-moi",
              "tr": "yeni-api",
              "cs": "nova-api",
              "el": "nea-api",
              "bg": "nova-api",
              "ru": "novaya-api",
              "uk": "nova-api",
              "hi": "naya-api",
              "th": "api-mai",
              "zh-CN": "xin-api",
              "ja": "atarashii-api",
              "zh-TW": "xin-api",
              "ko": "saeroun-api"
            }
          },
          {
            "value": "Unknown",
            "name": "Unknown",
            "name_localizations": {
              "id": "tidak-tahu",
              "da": "ukendt",
              "de": "unbekannt",
              "en-GB": "unknown",
              "en-US": "unknown",
              "es-ES": "desconocido",
              "es-419": "desconocido",
              "fr": "inconnue",
              "hr": "nepoznato",
              "it": "sconosciuto",
              "lt": "nezinoma",
              "hu": "ismeretlen",
              "nl": "onbekend",
              "no": "ukjent",
              "pl": "nieznany",
              "pt-BR": "desconhecido",
              "ro": "necunoscut",
              "fi": "tuntematon",
              "sv-SE": "okand",
              "vi": "khong-biet",
              "tr": "bilinmeyen",
              "cs": "neznamy",
              "el": "agnostos",
              "bg": "neizvestno",
              "ru": "neizvestno",
              "uk": "nevyznacheno",
              "hi": "agyat",
              "th": "mai-ru",
              "zh-CN": "wei-zhi",
              "ja": "fumei",
              "zh-TW": "wei-zhi",
              "ko": "al-su-eobsneun"
            }
          }
        ],
        "name_localizations": {
          "id": "kategori",
          "da": "kategori",
          "de": "kategorie",
          "en-GB": "category",
          "en-US": "category",
          "es-ES": "categoria",
          "es-419": "categoria",
          "fr": "categorie",
          "hr": "kategorija",
          "it": "categoria",
          "lt": "kategorija",
          "hu": "kategoria",
          "nl": "categorie",
          "no": "kategori",
          "pl": "kategoria",
          "pt-BR": "categoria",
          "ro": "categorie",
          "fi": "luokka",
          "sv-SE": "kategori",
          "vi": "loai",
          "tr": "kategori",
          "cs": "kategorie",
          "el": "katigoria",
          "bg": "kategoriya",
          "ru": "kategoriya",
          "uk": "kategoriya",
          "hi": "varg",
          "th": "hmwdhmu",
          "zh-CN": "leibie",
          "ja": "kategori",
          "zh-TW": "leibie",
          "ko": "beomju"
        }
      }
    ],
    "name_localizations": {
      "id": "laporan-bug",
      "da": "fejlrapport",
      "de": "fehlerbericht",
      "en-GB": "bug-report",
      "en-US": "bug-report",
      "es-ES": "informe-error",
      "es-419": "informe-error",
      "fr": "rapport-bug",
      "hr": "izvjestaj-o-greskama",
      "it": "rapporto-bug",
      "lt": "klaidos-ataskaita",
      "hu": "hibajelentes",
      "nl": "bugrapport",
      "no": "feilrapport",
      "pl": "raport-bledu",
      "pt-BR": "relatorio-bug",
      "ro": "raport-eroare",
      "fi": "virheraportti",
      "sv-SE": "buggrapport",
      "vi": "bao-cao-loi",
      "tr": "hata-raporu",
      "cs": "hlaseni-chyby",
      "el": "anafora-sfalmatos",
      "bg": "doklad-za-greshka",
      "ru": "otchet-ob-oshibke",
      "uk": "zvit-pro-pomylku",
      "hi": "truthi-riport",
      "th": "raingan-kho-phidphlad",
      "zh-CN": "cuo-wu-bao-gao",
      "ja": "bagu-ripooto",
      "zh-TW": "cuo-wu-bao-gao",
      "ko": "beogeu-bogoseo"
    }
  },
  code: `
  $let[b;
  $createChannel[$guildID;
  $option[category]-$option[severity]-$getGuildVar[a];
  GuildText;Bug: $option[description]
  Bug reporter: $username[$authorID]
  Severity: $option[severity]
  Category: $option[category];
  $getGuildVar[categoryID_in_which_reports_will_be_made]]]
  $let[z;
  $replaceText[$replaceText[$replaceText[$option[severity];High;#FF0000];Medium;#FFA500];Low;#32CD32]]
  $interactionReply[
  $ephemeral ### ✅ ¦ Bug report created
  Your bug report has been created in <#$get[b]>. Our development team will review it shortly.]
  $!addChannelPerms[$get[b];$authorID;AddReactions;ViewChannel;SendMessages;EmbedLinks;AttachFiles;ReadMessageHistory] 
  $let[pi;$sendMessage[$get[b];<@$authorID>
 $title[🐞 ¦ $option[category] Bug report initiated]
 $description[### Bug report details
> -# Please help us understand the issue by providing the following information:
        
        - Steps to reproduce the bug
        - Screen resolution
        - Browser and version
        - Operating system and version
        - Screenshots or screen recordings (if possible)
      ]
$color[$get[z]]
  $addActionRow
  $addButton[fixed;Mark as resolved;Success;;false];true]]
  $!pinMessage[$get[b];$get[pi]]
  $sendMessage[$getGuildVar[channelID_of_logs];New bug report is made at https://discord.com/channels/$guildID/$get[b]
  $title[$option[severity] severity bug has been reported]
  $description[Description of bug:\n> $cropText[$option[description];0;160;…]]
  $addField[Category:;$option[category];true]
  $addField[Bug report created by:;$username[$authorID];true]
  $color[$get[z]]
  $timestamp]

  $setGuildVar[severity-$get[b];$option[severity]]
  $setGuildVar[category-$get[b];$option[category]]
  $setGuildVar[description-$get[b];$option[description]]
  $setGuildVar[a;$sum[$getGuildVar[a];1]]
  `
}
