module.exports={
  data: {
  "name": "bug-report", // name
  "description": "Found a bug? Report now!", // description
  "options": // options
    // description of bugs
    {
      "type": 3,
      "name": "description",
      "description": "Detailed description of the bug",
      "required": true,
      // localizations
      "name_localizations": {
        "id": "keterangan",
        "da": "beskrivelse",
        "de": "Beschreibung",
        "en-GB": "description",
        "en-US": "description",
        "es-ES": "descripción",
        "es-419": "descripción",
        "fr": "description",
        "hr": "opis",
        "it": "descrizione",
        "lt": "Aprašymas",
        "hu": "leírás",
        "nl": "beschrijving",
        "no": "beskrivelse",
        "pl": "opis",
        "pt-BR": "descrição",
        "ro": "descriere",
        "fi": "kuvaus",
        "sv-SE": "beskrivning",
        "vi": "Sự miêu tả",
        "tr": "Tanım",
        "cs": "popis",
        "el": "περιγραφή",
        "bg": "Описание",
        "ru": "описание",
        "uk": "опис",
        "hi": "विवरण",
        "th": "คำอธิบาย",
        "zh-CN": "描述",
        "ja": "説明",
        "zh-TW": "描述",
        "ko": "설명"
      },
      "description_localizations": {
        "id": "Deskripsi terperinci tentang bug",
        "da": "Detaljeret beskrivelse af fejlen",
        "de": "Detaillierte Beschreibung des Fehlers",
        "en-GB": "Detailed description of the bug",
        "en-US": "Detailed description of the bug",
        "es-ES": "Descripción detallada del error",
        "es-419": "Descripción detallada del error",
        "fr": "Description détaillée du bogue",
        "hr": "Detaljan opis bube",
        "it": "Descrizione dettagliata del bug",
        "lt": "Išsamus klaidos aprašymas",
        "hu": "A hiba részletes leírása",
        "nl": "Gedetailleerde beschrijving van de bug",
        "no": "Detaljert beskrivelse av feilen",
        "pl": "Szczegółowy opis błędu",
        "pt-BR": "Descrição detalhada do bug",
        "ro": "Descrierea detaliată a bug -ului",
        "fi": "Yksityiskohtainen kuvaus virheestä",
        "sv-SE": "Detaljerad beskrivning av felet",
        "vi": "Mô tả chi tiết về lỗi",
        "tr": "Hatanın ayrıntılı açıklaması",
        "cs": "Podrobný popis chyby",
        "el": "Λεπτομερής περιγραφή του σφάλματος",
        "bg": "Подробно описание на грешката",
        "ru": "Подробное описание ошибки",
        "uk": "Детальний опис помилки",
        "hi": "बग का विस्तृत विवरण",
        "th": "คำอธิบายโดยละเอียดของข้อผิดพลาด",
        "zh-CN": "错误的详细说明",
        "ja": "バグの詳細な説明",
        "zh-TW": "錯誤的詳細說明",
        "ko": "버그에 대한 자세한 설명"
      }
    },
    {
    // bug report severity
      "type": 3,
      "name": "severity",
      "description": "Impact level of the bug",
      "required": true,
      // how severe the bug is
      "choices": [
        {
          "value": "High",
          "name": "High: Critical functionality impaired",
          // localization
          "name_localizations": {
            "id": "Tinggi: Gangguan fungsionalitas kritis",
            "da": "Høj: Kritisk funktionalitet nedsat",
            "de": "Hoch: Kritische Funktionalität beeinträchtigt",
            "en-GB": "High: Critical functionality impaired",
            "en-US": "High: Critical functionality impaired",
            "es-ES": "Alto: funcionalidad crítica deteriorada",
            "es-419": "Alto: funcionalidad crítica deteriorada",
            "fr": "Élevé: fonctionnalité critique altérée",
            "hr": "Visoko: Kritična funkcionalnost oštećena",
            "it": "Alto: funzionalità critica compromessa",
            "lt": "Aukštas: kritinis funkcionalumas sutriko",
            "hu": "Magas: A kritikus funkcionalitás romlott",
            "nl": "Hoog: kritische functionaliteit verminderd",
            "no": "Høy: kritisk funksjonalitet svekket",
            "pl": "Wysokie: krytyczna funkcjonalność upośledzona",
            "pt-BR": "Alta: funcionalidade crítica prejudicada",
            "ro": "Înalt: funcționalitate critică afectată",
            "fi": "Korkea: Kriittinen toiminnallisuus heikentynyt",
            "sv-SE": "Hög: kritisk funktionalitet nedsatt",
            "vi": "Cao: Chức năng quan trọng bị suy yếu",
            "tr": "Yüksek: Kritik işlevsellik bozuldu",
            "cs": "Vysoká: kritická funkce narušena",
            "el": "Υψηλή: εξασθεωμένη κρίσιμη λειτουργικότητα",
            "bg": "Висока: Критична функционалност е нарушена",
            "ru": "Высокий: критическая функциональность нарушена",
            "uk": "Високий: критична функціональність порушена",
            "hi": "उच्च: महत्वपूर्ण कार्यक्षमता बिगड़ा हुआ",
            "th": "สูง: การทำงานที่สำคัญบกพร่อง",
            "zh-CN": "高：关键功能受损",
            "ja": "高：重要な機能性が損なわれます",
            "zh-TW": "高：關鍵功能受損",
            "ko": "높음 : 중요한 기능이 손상되었습니다"
          }
        },
        {
          "value": "Medium",
          "name": "Medium: Moderate impact on user experience",
          // localization
          "name_localizations": {
            "id": "Sedang: Dampak Sedang pada Pengalaman Pengguna",
            "da": "Medium: Moderat indflydelse på brugeroplevelsen",
            "de": "Medium: moderate Auswirkungen auf die Benutzererfahrung",
            "en-GB": "Medium: Moderate impact on user experience",
            "en-US": "Medium: Moderate impact on user experience",
            "es-ES": "Medio: impacto moderado en la experiencia del usuario",
            "es-419": "Medio: impacto moderado en la experiencia del usuario",
            "fr": "Medium: impact modéré sur l'expérience utilisateur",
            "hr": "Srednji: Umjereni utjecaj na korisničko iskustvo",
            "it": "Medium: impatto moderato sull'esperienza dell'utente",
            "lt": "Vidutinis: vidutinis poveikis vartotojo patirčiai",
            "hu": "Közepes: Mérsékelt hatás a felhasználói élményre",
            "nl": "Medium: matige impact op gebruikerservaring",
            "no": "Medium: Moderat innvirkning på brukeropplevelsen",
            "pl": "Medium: Umiarkowany wpływ na wrażenia użytkownika",
            "pt-BR": "Médio: Impacto moderado na experiência do usuário",
            "ro": "Mediu: impact moderat asupra experienței utilizatorului",
            "fi": "Medium: Kohtalainen vaikutus käyttökokemukseen",
            "sv-SE": "Medium: Måttlig påverkan på användarupplevelsen",
            "vi": "Trung bình: Tác động vừa phải đến trải nghiệm người dùng",
            "tr": "Orta: Kullanıcı deneyimi üzerinde ılımlı etki",
            "cs": "Střední: Mírný dopad na uživatelský zážitek",
            "el": "Μεσαίο: Μέτριο αντίκτυπο στην εμπειρία των χρηστών",
            "bg": "Среден: Умерено въздействие върху потребителското изживяване",
            "ru": "Средний: Умеренное влияние на пользовательский опыт",
            "uk": "Середній: Помірний вплив на досвід користувача",
            "hi": "मध्यम: उपयोगकर्ता अनुभव पर मध्यम प्रभाव",
            "th": "ปานกลาง: ผลกระทบปานกลางต่อประสบการณ์ผู้ใช้",
            "zh-CN": "媒介：对用户体验的中等影响",
            "ja": "中：ユーザーエクスペリエンスへの適度な影響",
            "zh-TW": "媒介：對用戶體驗的中等影響",
            "ko": "매체 : 사용자 경험에 적당한 영향을 미칩니다"
          }
        },
        {
          "value": "Low",
          "name": "Low: Minimal disruption",
          // localization 
          "name_localizations": {
            "id": "Rendah: Gangguan minimal",
            "da": "Lav: Minimal forstyrrelse",
            "de": "Niedrig: Minimale Störung",
            "en-GB": "Low: Minimal disruption",
            "en-US": "Low: Minimal disruption",
            "es-ES": "Bajo: interrupción mínima",
            "es-419": "Bajo: interrupción mínima",
            "fr": "Faible: perturbation minimale",
            "hr": "Nisko: minimalni poremećaj",
            "it": "Basso: interruzione minima",
            "lt": "Žemas: minimalus sutrikimas",
            "hu": "Alacsony: Minimális zavar",
            "nl": "Laag: minimale verstoring",
            "no": "Lav: Minimal forstyrrelse",
            "pl": "Niski: minimalne zakłócenia",
            "pt-BR": "Baixo: interrupção mínima",
            "ro": "Scăzut: întrerupere minimă",
            "fi": "Matala: minimaalinen häiriö",
            "sv-SE": "Låg: Minimal störning",
            "vi": "Thấp: Sự gián đoạn tối thiểu",
            "tr": "Düşük: Minimum bozulma",
            "cs": "Nízká: minimální narušení",
            "el": "Χαμηλή: ελάχιστη διαταραχή",
            "bg": "Ниско: Минимално прекъсване",
            "ru": "Низкий: минимальное нарушение",
            "uk": "Низький: мінімальний зрив",
            "hi": "कम: न्यूनतम व्यवधान",
            "th": "ต่ำ: หยุดชะงักน้อยที่สุด",
            "zh-CN": "低：最小的破坏",
            "ja": "低：最小限の混乱",
            "zh-TW": "低：最小的破壞",
            "ko": "낮음 : 최소 혼란"
          }
        }
      ],
      // localisation 
      "name_localizations": {
        "id": "kerasnya",
        "da": "Alvorlighed",
        "de": "Schwere",
        "en-GB": "severity",
        "en-US": "severity",
        "es-ES": "gravedad",
        "es-419": "gravedad",
        "fr": "gravité",
        "hr": "ozbiljnost",
        "it": "gravità",
        "lt": "sunkumas",
        "hu": "súlyosság",
        "nl": "ernst",
        "no": "alvorlighetsgrad",
        "pl": "powaga",
        "pt-BR": "gravidade",
        "ro": "severitate",
        "fi": "vakavuus",
        "sv-SE": "stränghet",
        "vi": "mức độ nghiêm trọng",
        "tr": "şiddet",
        "cs": "závažnost",
        "el": "αυστηρότητα",
        "bg": "тежест",
        "ru": "тяжесть",
        "uk": "тяжкість",
        "hi": "गंभीरता",
        "th": "ความรุนแรง",
        "zh-CN": "严重程度",
        "ja": "重大度",
        "zh-TW": "嚴重程度",
        "ko": "심각성"
      }
    },
    {
      // category of bug reports 
      "type": 3,
      "name": "category",
      "description": "The Gluo project you want to make a report about.",
      "required": true,
      "choices": [
        // the categories of the reports and localisation 
        {
          "value": "Web",
          "name": "The Gluo web app",
          "name_localizations": {
            "id": "Aplikasi Web Gluo",
            "da": "Gluo -webappen",
            "de": "Die Gluo -Web -App",
            "en-GB": "The Gluo web app",
            "en-US": "The Gluo web app",
            "es-ES": "La aplicación web de gluo",
            "es-419": "La aplicación web de gluo",
            "fr": "L'application Web Gluo",
            "hr": "Gluo web aplikacija",
            "it": "L'app Web Gluo",
            "lt": "„Gluo“ žiniatinklio programa",
            "hu": "A Gluo webalkalmazás",
            "nl": "De Gluo Web App",
            "no": "Gluo Web -appen",
            "pl": "Aplikacja internetowa Gluo",
            "pt-BR": "O aplicativo da web Gluo",
            "ro": "Aplicația web Gluo",
            "fi": "Gluo -verkkosovellus",
            "sv-SE": "Gluo -webbappen",
            "vi": "Ứng dụng Web Gluo",
            "tr": "Gluo web uygulaması",
            "cs": "Webová aplikace Gluo",
            "el": "Η εφαρμογή Web Gluo",
            "bg": "Уеб приложението Gluo",
            "ru": "Gluo Web App",
            "uk": "Веб -додаток Gluo",
            "hi": "ग्लूओ वेब ऐप",
            "th": "แอปพลิเคชันเว็บ gluo",
            "zh-CN": "Gluo Web应用程序",
            "ja": "Gluo Webアプリ",
            "zh-TW": "Gluo Web應用程序",
            "ko": "Gluo 웹 앱"
          }
        },
        {
          "value": "App",
          "name": "The Gluo native app for andorid",
          "name_localizations": {
            "id": "Aplikasi asli Gluo untuk Andorid",
            "da": "Den indfødte app til gluo til Andorid",
            "de": "Die mit Gluo Native App für Andorid",
            "en-GB": "The Gluo native app for andorid",
            "en-US": "The Gluo native app for andorid",
            "es-ES": "La aplicación nativa de Gluo para Andorid",
            "es-419": "La aplicación nativa de Gluo para Andorid",
            "fr": "L'application native Gluo pour Andorid",
            "hr": "Nativna aplikacija Gluo za Andorid",
            "it": "L'app nativa Gluo per Andorid",
            "lt": "„Gluo“ gimtoji programa, skirta „Andorid“",
            "hu": "A Gluo natív alkalmazás Andorid számára",
            "nl": "De Gluo Native App voor Andorid",
            "no": "Gluo Native -appen for Andorid",
            "pl": "Natywna aplikacja Gluo dla Andorid",
            "pt-BR": "O aplicativo nativo de Gluo para Andorid",
            "ro": "Aplicația nativă Gluo pentru Andorid",
            "fi": "Andorid",
            "sv-SE": "Gluo Native -appen för Andorid",
            "vi": "Ứng dụng gốc Gluo cho Andorid",
            "tr": "Andorid için Gluo yerel uygulama",
            "cs": "Nativní aplikace Gluo pro Andorid",
            "el": "Η εφαρμογή Gluo για Andorid",
            "bg": "Приложението Gluo Native за Андорид",
            "ru": "Приложение Native Gluo для андорида",
            "uk": "Додаток Gluo Native для Andorid",
            "hi": "Andorid के लिए Gluo देशी ऐप",
            "th": "แอพ Gluo Native สำหรับ Andorid",
            "zh-CN": "Andorid的Gluo本地应用",
            "ja": "AndoridのGluoネイティブアプリ",
            "zh-TW": "Andorid的Gluo本地應用",
            "ko": "Andorid의 Gluo 기본 앱"
          }
        },
        {
          "value": "App 2",
          "name": "The new Gluo app",
          "name_localizations": {
            "id": "Aplikasi Gluo yang baru",
            "da": "Den nye Gluo -app",
            "de": "Die neue Gluo -App",
            "en-GB": "The new Gluo app",
            "en-US": "The new Gluo app",
            "es-ES": "La nueva aplicación Gluo",
            "es-419": "La nueva aplicación Gluo",
            "fr": "La nouvelle application Gluo",
            "hr": "Nova Gluo aplikacija",
            "it": "La nuova app Gluo",
            "lt": "Naujoji „Gluo“ programa",
            "hu": "Az új Gluo alkalmazás",
            "nl": "De nieuwe Gluo -app",
            "no": "Den nye Gluo -appen",
            "pl": "Nowa aplikacja Gluo",
            "pt-BR": "O novo aplicativo Gluo",
            "ro": "Noua aplicație Gluo",
            "fi": "Uusi Gluo -sovellus",
            "sv-SE": "Den nya Gluo -appen",
            "vi": "Ứng dụng Gluo mới",
            "tr": "Yeni Gluo uygulaması",
            "cs": "Nová aplikace Gluo",
            "el": "Η νέα εφαρμογή Gluo",
            "bg": "Новото приложение Gluo",
            "ru": "Новое приложение Gluo",
            "uk": "Новий додаток Gluo",
            "hi": "नया ग्लूओ ऐप",
            "th": "แอพ Gluo ใหม่",
            "zh-CN": "新的Gluo应用程序",
            "ja": "新しいGluoアプリ",
            "zh-TW": "新的Gluo應用程序",
            "ko": "새로운 Gluo 앱"
          }
        },
        {
          "value": "Api-4",
          "name": "The older Gluo api",
          "name_localizations": {
            "id": "API Gluo yang lebih tua",
            "da": "Den ældre gluo api",
            "de": "Die ältere Gluo -API",
            "en-GB": "The older Gluo api",
            "en-US": "The older Gluo api",
            "es-ES": "La API Gluo más antigua",
            "es-419": "La API Gluo más antigua",
            "fr": "L'ancienne API Gluo",
            "hr": "Stariji Gluo API",
            "it": "La vecchia API Gluo",
            "lt": "Senesnė „Gluo“ API",
            "hu": "Az idősebb Gluo API",
            "nl": "De oudere Gluo API",
            "no": "Den eldre Gluo API",
            "pl": "Starszy API Gluo",
            "pt-BR": "A API GLUO mais antiga",
            "ro": "API -ul gluo mai în vârstă",
            "fi": "Vanhempi Gluo -sovellusliittymä",
            "sv-SE": "Det äldre Gluo API",
            "vi": "API Gluo cũ hơn",
            "tr": "Eski Gluo API",
            "cs": "Starší API Gluo",
            "el": "Το παλαιότερο API Gluo",
            "bg": "По -старият Gluo API",
            "ru": "Старший Gluo API",
            "uk": "Старіший API Gluo",
            "hi": "पुराने ग्लूओ एपीआई",
            "th": "Gluo API รุ่นเก่า",
            "zh-CN": "较旧的Gluo API",
            "ja": "古いGluo API",
            "zh-TW": "較舊的Gluo API",
            "ko": "오래된 글루오 API"
          }
        },
        {
          "value": "Api-5",
          "name": "The newer Gluo api",
          "name_localizations": {
            "id": "API Gluo yang lebih baru",
            "da": "Den nyere Gluo API",
            "de": "Die neuere Gluo -API",
            "en-GB": "The newer Gluo api",
            "en-US": "The newer Gluo api",
            "es-ES": "La nueva API Gluo",
            "es-419": "La nueva API Gluo",
            "fr": "La nouvelle API Gluo",
            "hr": "Noviji Gluo API",
            "it": "La nuova API Gluo",
            "lt": "Naujesnė „Gluo“ API",
            "hu": "Az újabb Gluo API",
            "nl": "De nieuwere Gluo API",
            "no": "Den nyere Gluo API",
            "pl": "Nowszy API Gluo",
            "pt-BR": "A API GLUO mais recente",
            "ro": "Cea mai nouă API Gluo",
            "fi": "Uudempi Gluo -sovellusliittymä",
            "sv-SE": "Det nyare Gluo API",
            "vi": "API GLUO mới hơn",
            "tr": "Yeni Gluo API",
            "cs": "Novější API Gluo",
            "el": "Το νεότερο API Gluo",
            "bg": "По -новият Gluo API",
            "ru": "Новый Gluo API",
            "uk": "Новий API Gluo",
            "hi": "नया ग्लूओ एपीआई",
            "th": "Gluo API รุ่นใหม่",
            "zh-CN": "较新的Gluo API",
            "ja": "新しいGluo API",
            "zh-TW": "較新的Gluo API",
            "ko": "새로운 Gluo API"
          }
        },
        {
          "value": "Unknown",
          "name": "i don't know what i'm doing :/",
          "name_localizations": {
            "id": "Saya tidak tahu apa yang saya lakukan:/",
            "da": "Jeg ved ikke, hvad jeg laver:/",
            "de": "Ich weiß nicht, was ich tue:/",
            "en-GB": "i don't know what i'm doing :/",
            "en-US": "i don't know what i'm doing :/",
            "es-ES": "No sé lo que estoy haciendo:/",
            "es-419": "No sé lo que estoy haciendo:/",
            "fr": "Je ne sais pas ce que je fais: /",
            "hr": "Ne znam što radim:/",
            "it": "Non so cosa sto facendo:/",
            "lt": "Aš nežinau, ką darau:/",
            "hu": "Nem tudom, mit csinálok:/",
            "nl": "Ik weet niet wat ik doe:/",
            "no": "Jeg vet ikke hva jeg gjør:/",
            "pl": "Nie wiem, co robię:/",
            "pt-BR": "Eu não sei o que estou fazendo:/",
            "ro": "Nu știu ce fac:/",
            "fi": "En tiedä mitä teen:/",
            "sv-SE": "Jag vet inte vad jag gör:/",
            "vi": "Tôi không biết tôi đang làm gì:/",
            "tr": "Ne yaptığımı bilmiyorum:/",
            "cs": "Nevím, co dělám:/",
            "el": "Δεν ξέρω τι κάνω:/",
            "bg": "Не знам какво правя:/",
            "ru": "Я не знаю, что делаю:/",
            "uk": "Я не знаю, що роблю:/",
            "hi": "मुझे नहीं पता कि मैं क्या कर रहा हूं:/",
            "th": "ไม่รู้ว่ากำลังทำอะไรอยู่:/",
            "zh-CN": "我不知道我在做什么：/",
            "ja": "私が何をしているのかわからない：/",
            "zh-TW": "我不知道我在做什麼：/",
            "ko": "내가 뭘하는지 모르겠다 :/"
          }
        }
      ],
      "name_localizations": {
        "id": "kategori",
        "da": "kategori",
        "de": "Kategorie",
        "en-GB": "category",
        "en-US": "category",
        "es-ES": "categoría",
        "es-419": "categoría",
        "fr": "catégorie",
        "hr": "kategorija",
        "it": "categoria",
        "lt": "Kategorija",
        "hu": "kategória",
        "nl": "categorie",
        "no": "kategori",
        "pl": "kategoria",
        "pt-BR": "categoria",
        "ro": "categorie",
        "fi": "luokka",
        "sv-SE": "kategori",
        "vi": "loại",
        "tr": "kategori",
        "cs": "kategorie",
        "el": "κατηγορία",
        "bg": "категория",
        "ru": "категория",
        "uk": "категорія",
        "hi": "वर्ग",
        "th": "หมวดหมู่",
        "zh-CN": "类别",
        "ja": "カテゴリ",
        "zh-TW": "類別",
        "ko": "범주"
      },
      "description_localizations": {
        "id": "Proyek Gluo yang ingin Anda buat laporan.",
        "da": "Det gluo -projekt, du vil afgive en rapport om.",
        "de": "Das Gluo -Projekt, über das Sie einen Bericht erstellen möchten.",
        "en-GB": "The Gluo project you want to make a report about.",
        "en-US": "The Gluo project you want to make a report about.",
        "es-ES": "El proyecto GLUO al que desea hacer un informe.",
        "es-419": "El proyecto GLUO al que desea hacer un informe.",
        "fr": "Le projet Gluo sur lequel vous souhaitez faire un rapport.",
        "hr": "Gluo projekt o kojem želite dati izvještaj.",
        "it": "Il progetto Gluo su cui vuoi fare un rapporto.",
        "lt": "„Gluo“ projektas, apie kurį norite pateikti ataskaitą.",
        "hu": "A Gluo projekt, amiről jelentést szeretne készíteni.",
        "nl": "Het Gluo -project waarover u een rapport wilt maken.",
        "no": "Gluo -prosjektet du vil lage en rapport om.",
        "pl": "Projekt Gluo, o którym chcesz złożyć raport.",
        "pt-BR": "O projeto Gluo sobre o qual você deseja fazer um relatório.",
        "ro": "Proiectul Gluo despre care doriți să faceți un raport.",
        "fi": "GLUO -projekti, josta haluat tehdä raportin.",
        "sv-SE": "Gluo -projektet du vill göra en rapport om.",
        "vi": "Dự án Gluo bạn muốn làm một báo cáo về.",
        "tr": "Hakkında bir rapor yapmak istediğiniz Gluo projesi.",
        "cs": "Projekt Gluo, o kterém chcete podat zprávu.",
        "el": "Το έργο Gluo που θέλετε να κάνετε μια αναφορά.",
        "bg": "Проектът Gluo, за който искате да направите доклад.",
        "ru": "Проект GLUO, о котором вы хотите сделать отчет.",
        "uk": "Проект Gluo, про який ви хочете скласти звіт.",
        "hi": "जिस GLUO प्रोजेक्ट के बारे में आप एक रिपोर्ट बनाना चाहते हैं।",
        "th": "โครงการ GLUO ที่คุณต้องการทำรายงาน",
        "zh-CN": "您想报告的GLUO项目。",
        "ja": "レポートを作成したいGluoプロジェクト。",
        "zh-TW": "您想報告的GLUO項目。",
        "ko": "당신이보고하고 싶은 Gluo 프로젝트."
      }
    }
  ],
  "name_localizations": {
    "id": "Laporan Bug",
    "da": "Bug-rapporter",
    "de": "Fehlerbericht",
    "en-GB": "bug-report",
    "en-US": "bug-report",
    "es-ES": "informe de errores",
    "es-419": "informe de errores",
    "fr": "indicateur de bogue",
    "hr": "report",
    "it": "report di bug",
    "lt": "klaidų ataskaita",
    "hu": "hibajelentés",
    "nl": "bugrapport",
    "no": "Feilrapport",
    "pl": "raport błędu",
    "pt-BR": "relatório de bug",
    "ro": "Raportul de erori",
    "fi": "virhekortti",
    "sv-SE": "buggrapport",
    "vi": "Báo cáo lỗi",
    "tr": "hata raporu",
    "cs": "Report chyby",
    "el": "αναφορά για τα σφάλματα",
    "bg": "Отчет на бъгове",
    "ru": "отчет об ошибках",
    "uk": "звіт про помилку",
    "hi": "बग-रिपोर्ट",
    "th": "รายงานข้อผิดพลาด",
    "zh-CN": "错误报告",
    "ja": "バグレポート",
    "zh-TW": "錯誤報告",
    "ko": "버그보고"
  },
  "description_localizations": {
    "id": "Menemukan bug? ",
    "da": "Fundet en fejl? ",
    "de": "Einen Fehler gefunden? ",
    "en-GB": "Found a bug? Report now!",
    "en-US": "Found a bug? Report now!",
    "es-ES": "Encontrado un error? ",
    "es-419": "Encontrado un error? ",
    "fr": "Vous avez trouvé un bug? ",
    "hr": "Pronašli bugu? ",
    "it": "Hai trovato un bug? ",
    "lt": "Radote klaidą? ",
    "hu": "Talált egy hibát? ",
    "nl": "Een bug gevonden? ",
    "no": "Fant en feil? ",
    "pl": "Znalazłeś błąd? ",
    "pt-BR": "Encontrou um bug? ",
    "ro": "Ai găsit un bug? ",
    "fi": "Löysitkö virheen? ",
    "sv-SE": "Hittade ett fel? ",
    "vi": "Tìm thấy một lỗi? ",
    "tr": "Bir hata mı buldun? ",
    "cs": "Našli chybu? ",
    "el": "Βρήκατε ένα σφάλμα; ",
    "bg": "Намери грешка? ",
    "ru": "Нашел ошибку? ",
    "uk": "Знайшов помилку? ",
    "hi": "एक बग मिला? ",
    "th": "พบข้อผิดพลาด? ",
    "zh-CN": "找到一个错误？",
    "ja": "バグを見つけましたか？",
    "zh-TW": "找到一個錯誤？立即報告！",
    "ko": "버그를 찾았습니까? "
  }
            },
  code: `
  $let[b;
  $createChannel[$guildID;
  $option[category]-$option[severity]-$getGuildVar[a];
  GuildText;Bug: $option[description]
  Bug reporter: $username[$authorID]
  Severity: $option[severity]
  Category: $option[category];
  $getGuildVar[categoryID_in_which_reports_will_be_made]]]
  $let[z;
  $replaceText[$replaceText[$replaceText[$option[severity];High;#FF0000];Medium;#FFA500];Low;#32CD32]]
  $interactionReply[
  $ephemeral ### ✅ ¦ Bug report created
  Your bug report has been created in <#$get[b]>. Our development team will review it shortly.]
  $!addChannelPerms[$get[b];$authorID;AddReactions;ViewChannel;SendMessages;EmbedLinks;AttachFiles;ReadMessageHistory] 
  $let[pi;$sendMessage[$get[b];<@$authorID>
 $title[🐞 ¦ $option[category] Bug report initiated]
 $description[### Bug report details
> -# Please help us understand the issue by providing the following information:
        
        - Steps to reproduce the bug
        - Screen resolution
        - Browser and version
        - Operating system and version
        - Screenshots or screen recordings (if possible)
      ]
$color[$get[z]]
  $addActionRow
  $addButton[fixed;Mark as resolved;Success;;false];true]]
  $!pinMessage[$get[b];$get[pi]]
  $sendMessage[$getGuildVar[channelID_of_logs];New bug report is made at https://discord.com/channels/$guildID/$get[b]
  $title[$option[severity] severity bug has been reported]
  $description[Description of bug:\n> $cropText[$option[description];0;160;…]]
  $addField[Category:;$option[category];true]
  $addField[Bug report created by:;$username[$authorID];true]
  $color[$get[z]]
  $timestamp]

  $setGuildVar[severity-$get[b];$option[severity]]
  $setGuildVar[category-$get[b];$option[category]]
  $setGuildVar[description-$get[b];$option[description]]
  $setGuildVar[a;$sum[$getGuildVar[a];1]]
  `
}
