module.exports={
  data: {
    "type": 1,
    "description": "Check how my response times are",
    "name": "ping",
    "description_localizations": {
      "id": "Periksa bagaimana waktu respons saya",
      "da": "Kontroller, hvordan mine responstider er",
      "de": "Überprüfen Sie, wie meine Antwortzeiten sind",
      "en-GB": "Check how my response times are",
      "en-US": "Check how my response times are",
      "es-ES": "Verifique cómo son mis tiempos de respuesta",
      "es-419": "Verifique cómo son mis tiempos de respuesta",
      "fr": "Vérifiez comment mes temps de réponse sont",
      "hr": "Provjerite kako su moja vremena odgovora",
      "it": "Controlla come sono i miei tempi di risposta",
      "lt": "Patikrinkite, kaip yra mano atsakymo laikas",
      "hu": "Ellenőrizze, hogy vannak a válaszadási időm",
      "nl": "Controleer hoe mijn responstijden zijn",
      "no": "Sjekk hvordan responstidene mine er",
      "pl": "Sprawdź, jak są moje czasy odpowiedzi",
      "pt-BR": "Verifique como meus tempos de resposta são",
      "ro": "Verificați cum sunt timpul meu de răspuns",
      "fi": "Tarkista, kuinka vastausajat ovat",
      "sv-SE": "Kontrollera hur mina responstider är",
      "vi": "Kiểm tra thời gian phản hồi của tôi như thế nào",
      "tr": "Yanıt sürelerimin nasıl olduğunu kontrol edin",
      "cs": "Zkontrolujte, jak jsou moje doby odezvy",
      "el": "Ελέγξτε πώς είναι οι χρόνοι απόκρισης μου",
      "bg": "Проверете как са моите времена за реакция",
      "ru": "Проверьте, как мое время ответа",
      "uk": "Перевірте, наскільки мої часи відповіді",
      "hi": "जाँच करें कि मेरी प्रतिक्रिया समय कैसा है",
      "th": "ตรวจสอบว่าเวลาตอบสนองของฉันเป็นอย่างไร",
      "zh-CN": "检查我的响应时间",
      "ja": "応答時間がどのようになっているかを確認してください",
      "zh-TW": "檢查我的響應時間",
      "ko": "내 응답 시간이 어땠는지 확인하십시오"
  }
  },
  code: `I can respond to you in $round[$ping;2]ms.`
} 
