module.exports={
  data: {
  "type": 1,
  "description": "Shows the statistics of the bug reports",
  "name": "statistics",
  "name_localizations": {
    "id": "statistik",
    "da": "statistik",
    "de": "Statistiken",
    "en-GB": "statistics",
    "en-US": "statistics",
    "es-ES": "estadística",
    "es-419": "estadística",
    "fr": "statistiques",
    "hr": "statistika",
    "it": "statistiche",
    "lt": "statistika",
    "hu": "statisztika",
    "nl": "statistieken",
    "no": "statistikk",
    "pl": "statystyka",
    "pt-BR": "Estatística",
    "ro": "Statistici",
    "fi": "tilastot",
    "sv-SE": "statistik",
    "vi": "Thống kê",
    "tr": "istatistik",
    "cs": "statistika",
    "el": "στατιστική",
    "bg": "Статистика",
    "ru": "статистика",
    "uk": "статистика",
    "hi": "आंकड़े",
    "th": "สถิติ",
    "zh-CN": "统计数据",
    "ja": "統計",
    "zh-TW": "統計數據",
    "ko": "통계"
  },
  "description_localizations": {
    "id": "Menunjukkan statistik laporan bug",
    "da": "Viser statistikken over fejlrapporterne",
    "de": "Zeigt die Statistiken der Fehlerberichte",
    "en-GB": "Shows the statistics of the bug reports",
    "en-US": "Shows the statistics of the bug reports",
    "es-ES": "Muestra las estadísticas de los informes de errores",
    "es-419": "Muestra las estadísticas de los informes de errores",
    "fr": "Montre les statistiques des rapports de bogues",
    "hr": "Prikazuje statistiku izvještaja o pogrešci",
    "it": "Mostra le statistiche dei rapporti sui bug",
    "lt": "Parodo pranešimų apie klaidas statistiką",
    "hu": "Mutatja a hibajelentések statisztikáit",
    "nl": "Toont de statistieken van de bugrapporten",
    "no": "Viser statistikken over feilrapportene",
    "pl": "Pokazuje statystyki raportów błędów",
    "pt-BR": "Mostra as estatísticas dos relatórios de bug",
    "ro": "Arată statisticile rapoartelor de erori",
    "fi": "Näyttää vikaraporttien tilastot",
    "sv-SE": "Visar statistiken från felrapporterna",
    "vi": "Hiển thị số liệu thống kê của các báo cáo lỗi",
    "tr": "Hata raporlarının istatistiklerini gösterir",
    "cs": "Ukazuje statistiky zpráv o chybách",
    "el": "Δείχνει τα στατιστικά στοιχεία των αναφορών σφαλμάτων",
    "bg": "Показва статистиката на докладите за грешки",
    "ru": "Показывает статистику сообщений об ошибках",
    "uk": "Показана статистика звітів про помилки",
    "hi": "बग रिपोर्ट के आंकड़े दिखाते हैं",
    "th": "แสดงสถิติของรายงานข้อผิดพลาด",
    "zh-CN": "显示错误报告的统计信息",
    "ja": "バグレポートの統計を示します",
    "zh-TW": "顯示錯誤報告的統計信息",
    "ko": "버그 보고서의 통계를 보여줍니다"
  }
  },
  code:`$let[cr;$sub[$sub[$getGuildVar[a];1];
  $channelChildrenCount[$getGuildVar[categoryID_in_which_reports_will_be_made]]]]
  $title[📊 ¦ Bug Report Statistics]
  $description[**Closed vs Total bug reports**
  > $bar[$get[cr];$sub[$getGuildVar[a];1];20] ($trunc[$math[$get[cr]/$getGuildVar[a] * 100]]%)] $footer[Last updated]$timestamp$color[Blurple]`,
}
